---
traces: 
  - path: "/users/smiano/maestro-eval/pcaps/uniform_64B.pcap"
    tx_queues: 4
  - path: "/users/smiano/maestro-eval/pcaps/uniform_64B.pcap"
    tx_queues: 4
  - path: "/users/smiano/maestro-eval/pcaps/uniform_64B.pcap"
    tx_queues: 4
  - path: "/users/smiano/maestro-eval/pcaps/uniform_64B.pcap"
    tx_queues: 4
  - path: "/users/smiano/maestro-eval/pcaps/uniform_64B.pcap"
    tx_queues: 4
  - path: "/users/smiano/maestro-eval/pcaps/uniform_64B.pcap"
    tx_queues: 4
numacore: 0
nbruns: 100000000
timeout: 30
max_mpps: 100
max_mbps: -1
write_csv: True
wait_enter: False
slow_mode: False
stats:
  - pci_id: 0000:51:00.0
    file_name: "result_v2_core1.csv"
send_port_pci: 0000:51:00.0
loglevel: TRACE

